### ISSUE TITLE
Nice work!!

### ISSUE THREAD

**Issue by cod3r-dev** [Zeeshanahmad4/Facebook-Automation-bot-with-Multilogin-and-Proxies#1]
Can i ask you ???

If i have the multilogin on a server !! How i can run the script and control the remote profiles from other pc on same vpn network?

**Comment by Zeeshanahmad4** [comment]
You should have a look at the "Celery"
it is a Distributed Task Queue which communicates using messages. 


http://www.celeryproject.org/

**Comment by Zeeshanahmad4** [comment]
You should have a look at the "Celery"
it is a Distributed Task Queue which communicates using messages.

http://www.celeryproject.org/
