### ISSUE TITLE
Creating Accounts Functions

### ISSUE THREAD

**Issue by bizfreak22** [Zeeshanahmad4/Facebook-Automation-bot-with-Multilogin-and-Proxies#2]
Hey, have you thought about adding functions to create new accounts?

Great job btw 😀

**Comment by Zeeshanahmad4** [comment]
create new accounts of what?
Facebook or Multilogin ?

**Comment by bizfreak22** [comment]
> create new accounts of what?
> Facebook or Multilogin ?

Facebook..

**Comment by Zeeshanahmad4** [comment]
Maybe in the future, nowadays I am busy with the some other projects.
